 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: katib-ui
   namespace: katib
 spec:
  rules:
    - host: modeldb-frontend.ingress.hpsearch.us-east-1.k8s.lyft.net
      http:
        paths:
          - backend:
              serviceName: modeldb-frontend
              servicePort: 443
