apiVersion: v1
kind: Service
metadata:
  name: modeldb-frontend
  namespace: katib
  labels:
    app: modeldb
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: ui
  selector:
    app: modeldb
    component: frontend
